#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2017 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
# set spacevim theme. by default colorscheme layer is not loaded,
# if you want to use more colorscheme, please load the colorscheme
# layer
colorscheme = "gruvbox"
background = "dark"
# Disable guicolors in basic mode, many terminal do not support 24bit
# true colors
enable_guicolors = true
# Disable statusline separator, if you want to use other value, please
# install nerd fonts
statusline_separator = "arrow"
statusline_inactive_separator = "arrow"
buffer_index_type = 4
enable_tabline_filetype_icon = true
enable_statusline_display_mode = false
default_indent = 4
bootstrap_after = "myconfig#after"
bootstrap_before = "myconfig#before"
guifont = "Hack Nerd Font:h11"
enable_neomake = false
enable_ycm = 0
enableWcwidth = 1

# Enable autocomplete layer
[[layers]]
name = 'autocomplete'
auto-completion-return-key-behavior = "complete"
auto-completion-tab-key-behavior = "smart"

[[layers]]
name = 'shell'
default_position = 'top'
default_height = 30

[[layers]]
name = "git"

[[layers]]
name = "VersionControl"

[[layers]]
name = "lang#markdown"

[[layers]]
name = "denite"

[[layers]]
name = "lang#vim"

[[custom_plugins]]
name = "cespare/vim-toml"
merged = 0

[[custom_plugins]]
name = "junegunn/goyo.vim"
merged = 0

[[custom_plugins]]
name = "junegunn/limelight.vim"
merged = 0

[[custom_plugins]]
name = "junegunn/vim-easy-align"
merged = 0

[[custom_plugins]]
name = "terryma/vim-multiple-cursors"
merged = 0

[[custom_plugins]]
name = "tpope/vim-abolish"
merged = 0

[[custom_plugins]]
name = "dhruvasagar/vim-table-mode"
merged = 0

[[custom_plugins]]
name = "godlygeek/tabular"
merged = 0

[[custom_plugins]]
name = "mbbill/undotree"
merged = 0

[[custom_plugins]]
name = "posva/vim-vue"
merged = 0

[[custom_plugins]]
name = "dbeniamine/cheat.sh-vim"
merged = 0
